### ISSUE TITLE
Problema de instalación.

### ISSUE THREAD

**Issue by franciscovela** [GobiernoLaRioja/forestroaddesigner#5]
Buen día,  utilizo Qgis 3.8.2-Zanzibar.
Quise probar el Plugin Forest Road Designer.
Primero no aparece en la ventana de complementos. Luego lo descargúe de Github y no lo pude instalar mediante el ZIP.  Marca el siguiente error.:
..."
**No se pudo cargar el complemento 'forestroaddesigner' debido a un error al llamar a su método classFactory() 

ImportError: PyQt4 classes cannot be imported in QGIS 3.x. Use PyQt5.QtCore or the version independent qgis.PyQt.QtCore import instead. 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\forestroaddesigner\__init__.py", line 43, in classFactory
    from .forest_road_designer import ForestRoadDesigner
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\forestroaddesigner\forest_road_designer.py", line 34, in 
    from PyQt4.QtCore import QSettings, QTranslator, qVersion, QCoreApplication, Qt
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 735, in _import
    raise ImportError(msg)
ImportError: PyQt4 classes cannot be imported in QGIS 3.x.
Use PyQt5.QtCore or the version independent qgis.PyQt.QtCore import instead.

Versión de Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versión de QGIS: 3.8.2-Zanzibar Zanzibar, 4470baa1a3 

Ruta de Python:
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ForestRoadsNetworksUPLOAD
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\BoundaryDelineation-master/lib
C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.8\bin\python37.zip
C:\PROGRA~1\QGIS3~1.8\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib
C:\PROGRA~1\QGIS3~1.8\bin
C:\PROGRA~1\QGIS3~1.8\apps\Python37
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Usuario\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\Usuario\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2mapillary
C:\Users\Usuario\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2mapillary\extlibs
F:/002 IGN/999_ANILLO_REGIONAL
C:\Users\Usuario\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\Usuario\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools**"...

Algún comentario...
Muchas gracias.
Francisco Vela.

**Comment by pmperez-larioja** [comment]
Siento el retraso en la respuesta.
Vamos a publicar una nueva versión. Esperamos que no vuelvan a aparecer estos errores.
